cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

mealplanner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('main.urls')),
    path('orders/', include('order.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>{% block title %} {% endblock%}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css'%}" />
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
								</header>
                        {% block content%}{% endblock%}
						</div>
					</div>

				<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<form method="get" action="{% url 'home' %}">
										<input type="text" name="q" id="query" placeholder="Search" />
									</form>
								</section>

							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="{% url 'home' %}">All the Food</a></li>
										<li>
											<span class="opener">Food Companies</span>
											<ul>
												{%for company in companies %}
												<li><a href="{% url 'company' company.slug %}">{{ company }}</a></li>
												{% endfor %}
											</ul>
										</li>
									</ul>
								</nav>


							<!-- Section -->


							<!-- Footer -->


						</div>
					</div>

			</div>

		<!-- Scripts -->
	<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js'%}"></script>
			<script src="{% static 'assets/js/util.js'% }"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>


	</body>
</html>

templates/company_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
							<!-- Banner -->
								<section id="banner">
									<div class="content">
										<header>
											<h1>{{ company.name }}</h1>
<!--											<p>A free and fully responsive site template</p>-->
										</header>
			
										{% if company.get_children %}
										{% for child in company.get_children %}
										<a href="{% url 'company' child.slug %}"><li>{{ child.name }}</li></a>
										{% endfor %}
										{% endif %}
									</div>
									<span class="image object">
										<img src="{{ company.image.url }}" style="width: 400px; height: 300px;" alt="..." />
									</span>
								</section>


							<!-- Section -->
							{% if not company.get_children %}
								<section>
									<header class="major">
										<h2>Available food</h2>
									</header>
									<div class="posts">
										{% for food in foods%}
										<article>
											<a href="#" class="image"><img src="{{ food.image.url }}" style="width: 300px; height: 250px;" alt="" /></a>
											<h3>{{ food }}</h3>
											<p>{{ food.description| truncatewords:20 }}</p>
											<ul class="actions">
												<li><a href="{% url 'detail' food.id %}" class="button">More</a></li>
											</ul>
										</article>
										{% endfor %}
									</div>
								</section>
						{% endif %}
{% endblock %}


templates/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Checkout</h4>
                <form enctype="multipart/form-data" action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    <input type="submit" class="btn btn-primary" value="Submit order">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }}
                        <span>Kshs. {{ item.total_price }}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: {{ cart.get_total_price }}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %}

templates/created.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
                <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 1 %}
                        My Shopping Order:
                        <h1>here</h1>
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }},  {{ cart.get_total_price }} Taka.
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    <h1>hi</h1>
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>Taka. {{ item.price }}</td>
                            <td>Taka. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>Taka. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "home" %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}

templates/food_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<!-- Content -->
		<section>
			<header class="main">
				<h1>{{ food.title }}</h1>
			</header>

			<span class="image main"><img src="{{ food.image.url }}" style="width: 450; height: 500;" alt="" /></span>

			<p>Price: {{ food.price }} c</p>

			{{food.id}}

			<form enctype="multipart/form-data" action="{% url "cart:cart_add" food.id %}" method="post" >
				{% csrf_token %}
				{{ cart_product_form }}
				<input type="submit" value="add to cart" class="btn btn-primary">
			</form>

			<hr class="major" />
			{%for image in images %}
		<img src="{{ image.url }}" style="width: 450px; height: 450px;" class="img-thumbnail" alt="...">
			{% endfor %}


		</section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Content -->
	<section>
		<header class="main">
			<h1>Food Ordering</h1>
		</header>



		
		<hr class="major" />

			<div class="posts">
				{% for food in page_obj%}
				<article>
					<a href="#" class="image"><img src="{{ food.image.url }}" style="width: 295px; height: 225px;" alt="" /></a>
					<h3>{{ food }}</h3>
					<p>{{ food.price}} c</p>
					<ul class="actions">
						<li><a href="{% url 'detail' food.id %}" class="button">More</a></li>
					</ul>
				</article>
				{% endfor %}
			</div>
	</section>
<nav aria-label="...">
  <ul class="pagination pagination-sm">
	  {% if page_obj.has_previous %}
	  <li class="page-item"><a class="page-link" href="{% url 'home'%}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
	{% endif %}
    <li class="page-item active" aria-current="page">
      <span class="page-link">{{page_obj.number }}</span>
    </li>
	  {%if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="{% url 'home'%}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
	{% endif %}
  </ul>
</nav>
{% endblock %}


templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Search results</h1>
	<div class="posts">
				{% for food in foods%}
				<article>
					<a href="#" class="image"><img src="{{ food.get_image }}" style="width: 300px; height: 250px;" alt="" /></a>
					<h3>{{ food }}</h3>
					<p>{{ food.price}} c </p>
					<ul class="actions">
						<li><a href="{% url 'detail' food.id %}" class="button">More</a></li>
					</ul>
				</article>
				{% endfor %}
			</div>
{% endblock %}